theme: jekyll-theme-minimal
title: Timothy Scoppetta Resume & Employment Info
description: "[Contact](https://docs.google.com/forms/d/e/1FAIpQLSe-9TaezZnGlpn2AUmiz1jOV62KyrxAqUTI65bY8Sm-srqSiw/viewform)"
github:
  is_project_page: false
